# Generated by Django 4.2.1 on 2023-05-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0042_rename_atégorie_product_catégorie"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="catégorie",),
        migrations.RemoveField(model_name="product", name="fournisseur",),
    ]
