# Generated by Django 4.2.1 on 2023-05-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0043_remove_product_catégorie_remove_product_fournisseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catégorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magasin.categorie",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fournisseur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="magasin.fournisseur",
            ),
        ),
    ]
